#!/usr/bin/env python3
"""Export the locked dependencies plus the reviewed Intel wheel's exact hash."""

import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def with_bundled_hash(requirements, directory):
    directory = directory.resolve()
    manifest = json.loads((directory / 'manifest.json').read_text())
    name = manifest['wheel']
    if (manifest['distribution'] != 'cryptography' or not isinstance(name, str) or
            Path(name).name != name or not name.startswith('cryptography-') or
            not name.endswith('_x86_64.whl')):
        raise ValueError('Invalid Intel wheel manifest')
    wheel = directory / name
    if (wheel.resolve() != wheel.absolute() or not wheel.is_file() or
            hashlib.sha256(wheel.read_bytes()).hexdigest() != manifest['sha256']):
        raise ValueError('Bundled Intel wheel SHA-256 mismatch')
    pattern = re.compile(r'^cryptography==' + re.escape(manifest['version']) + r' \\$', re.M)
    if len(pattern.findall(requirements)) != 1:
        raise ValueError('Rebuild the Intel wheel for the locked cryptography version')
    return pattern.sub(lambda match: match[0] + '\n    --hash=sha256:' + manifest['sha256'] + ' \\', requirements)


def export():
    original = subprocess.check_output([
        'uv', 'export', '--locked', '--format', 'requirements-txt', '--no-dev',
        '--no-emit-project', '--no-header'], cwd=ROOT, text=True)
    return '# Generated by python scripts/export_requirements.py; do not edit.\n' + \
        with_bundled_hash(original, ROOT / 'packaging/wheels')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / 'packaging/requirements.txt'
    content = export()
    if args.check:
        if target.read_text() != content:
            parser.exit(1, 'Run python scripts/export_requirements.py to refresh packaged dependency hashes\n')
        print('Packaged dependency hashes match uv.lock and the bundled Intel wheel')
    else:
        target.write_text(content)
